## Script Based Questions:
1. Write a program to take a name and age from the user and print a greeting message.
2. Create a list of numbers and print only even numbers using a for loop.
3. Write a program that handles division by zero using try-except.
4. Given a string, count how many vowels it has.
5. Reverse a list without using built-in functions.
6. Create a dictionary with at least 5 key-value pairs and print them.
7. Write a Pandas code to read a CSV and print the top 5 rows.
8. Create a DataFrame from a Python dictionary.
9. Replace all missing values in a DataFrame with the column’s mean.
10. Filter rows in a DataFrame where the "Age" column is greater than 30.

In [3]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Aishwarya', 'Bikram', 'Cheetah', 'Dev', 'Esha', 'Farhan', 'Gauri', 'Hari'],
    'Age': [25.0, 42.0, np.nan, 31.0, 19.0, 56.0, np.nan, 28.0],
    'Department': ['HR', 'IT', 'Ops', 'IT', 'Marketing', 'Finance', 'Ops', 'HR'],
    'Salary': [50000.0, 85000.0, 62000.0, np.nan, 45000.0, 95000.0, np.nan, 52000.0],
    'Sample_Numbers':[12, 7, 22, 15, 40, 33, 8, 19],
    'Vowel_Test_Strings': ['apple', 'sky', 'education', 'rhythm', 'beautiful', 'xyz', 'ice', 'queue']
}

emp_data= pd.DataFrame(data)

emp_data.to_excel('practice_data.xlsx', index=False)

In [6]:
emp_data

        Name   Age Department   Salary  Sample_Numbers Vowel_Test_Strings
0  Aishwarya  25.0         HR  50000.0              12              apple
1     Bikram  42.0         IT  85000.0               7                sky
2    Cheetah   NaN        Ops  62000.0              22          education
3        Dev  31.0         IT      NaN              15             rhythm
4       Esha  19.0  Marketing  45000.0              40          beautiful
5     Farhan  56.0    Finance  95000.0              33                xyz
6      Gauri   NaN        Ops      NaN               8                ice
7       Hari  28.0         HR  52000.0              19              queue

In [5]:
User_Name = str(input())
User_Age = int(input())
print("Thank you for logging in again !!")

 Cheetah
 19

Thank you for logging in again !!

In [10]:
Numbers = [1,2,3,4,5,23,4,34,32,2312,23,53,223]
Even_list=[]
for num in Numbers[0:]:
    if num%2==0:
        Even_list.append(num)

Even_list

[2, 4, 4, 34, 32, 2312]

In [18]:
Dividant= int(input("Enter the number to be divided"))
Divider = int(input("Enter the number which divide the dividant"))

def Division(Dividant,Divider):
        return Dividant/Divider
try:
    result = Division(Dividant,Divider)
    print("The answer is",result)

except ZeroDivisionError:
    print("Please enter a number more than 0")

Enter the number to be divided 65
Enter the number which divide the dividant 0

Please enter a number more than 0

In [23]:
# vowels=['a','e','i','o','u']
# input_string = str(input())
# count=0
# for char in input_string:
#     if char.lower() in "aeiou":
#         count+=1
# print("Vowels count:",count)

text = input("Enter a string: ")

count = sum(1 for char in text if char.lower() in "aeiou")

print("Number of vowels:", count)

Enter a string:  jameoys

Number of vowels: 3

In [29]:
# Method 1
List = [1,2,3,4,5,6,7,8,9]
print(List[::-1])

# Method 2
List2= [10,20,30,40,50,60]
left = 0
right = len(List2)-1
while left<right:
    List2[left],List2[right]=List2[right],List2[left]
    left+=1
    right-=1

print(List2)

[9, 8, 7, 6, 5, 4, 3, 2, 1]
[60, 50, 40, 30, 20, 10]

In [3]:
import pandas as pd
Students = { "Name":"Yuvasree",
             "Age": 23,
             "Sex": "Female",
             "Qualification":"B.tech",
             "Experienced": "8 Months"}
Students.items()

dict_items([('Name', 'Yuvasree'), ('Age', 23), ('Sex', 'Female'), ('Qualification', 'B.tech'), ('Experienced', '8 Months')])

In [4]:
pd.read_csv("insurance.csv").head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [46]:
import pandas as pd
import numpy as np
# Students = { "Name": ["Yuvasree","Hari","Kamal","Munu"],
#              "Age":[ 23,24,np.nan,22],
#              "Sex": ["Female","Male","Male","Male"],
#              "Qualification":["B.tech","B.E","B.Tech","B.E"],
#              "Experienced": ["8 Months","1 year","2 years",np.nan]}
# pd.DataFrame(Students)

data = {
    'Name': ['Aishwarya', 'Bikram', 'Cheetah', 'Dev', 'Esha', 'Farhan', 'Gauri', 'Hari'],
    'Age': [25.0, 42.0, np.nan, 31.0, 19.0, 56.0, np.nan, 28.0],
    'Department': ['HR', 'IT', 'Ops', 'IT', 'Marketing', 'Finance', 'Ops', 'HR'],
    'Salary': [50000.0, 85000.0, 62000.0, np.nan, 45000.0, 95000.0, np.nan, 52000.0],
    'Sample_Numbers': [12, 7, 22, 15, 40, 33, 8, 19],
    'Vowel_Test_Strings': ['apple', 'sky', 'education', 'rhythm', 'beautiful', 'xyz', 'ice', 'queue']
}
Employee_data=pd.DataFrame(data)
Employee_data

        Name   Age Department   Salary  Sample_Numbers Vowel_Test_Strings
0  Aishwarya  25.0         HR  50000.0              12              apple
1     Bikram  42.0         IT  85000.0               7                sky
2    Cheetah   NaN        Ops  62000.0              22          education
3        Dev  31.0         IT      NaN              15             rhythm
4       Esha  19.0  Marketing  45000.0              40          beautiful
5     Farhan  56.0    Finance  95000.0              33                xyz
6      Gauri   NaN        Ops      NaN               8                ice
7       Hari  28.0         HR  52000.0              19              queue

In [47]:
Employee_data.isnull().sum()

Name                  0
Age                   2
Department            0
Salary                2
Sample_Numbers        0
Vowel_Test_Strings    0
dtype: int64

In [48]:
Employee_data.loc[Employee_data["Age"].isna(),"Age"] = Employee_data["Age"].mean()
Employee_data

        Name   Age Department   Salary  Sample_Numbers Vowel_Test_Strings
0  Aishwarya  25.0         HR  50000.0              12              apple
1     Bikram  42.0         IT  85000.0               7                sky
2    Cheetah  33.5        Ops  62000.0              22          education
3        Dev  31.0         IT      NaN              15             rhythm
4       Esha  19.0  Marketing  45000.0              40          beautiful
5     Farhan  56.0    Finance  95000.0              33                xyz
6      Gauri  33.5        Ops      NaN               8                ice
7       Hari  28.0         HR  52000.0              19              queue

In [49]:
Employee_data.loc[Employee_data["Salary"].isna(),"Salary"]=Employee_data["Salary"].mean()
Employee_data

        Name   Age Department        Salary  Sample_Numbers Vowel_Test_Strings
0  Aishwarya  25.0         HR  50000.000000              12              apple
1     Bikram  42.0         IT  85000.000000               7                sky
2    Cheetah  33.5        Ops  62000.000000              22          education
3        Dev  31.0         IT  64833.333333              15             rhythm
4       Esha  19.0  Marketing  45000.000000              40          beautiful
5     Farhan  56.0    Finance  95000.000000              33                xyz
6      Gauri  33.5        Ops  64833.333333               8                ice
7       Hari  28.0         HR  52000.000000              19              queue

In [57]:
Employee_data[Employee_data["Age"]>30]

      Name   Age Department        Salary  Sample_Numbers Vowel_Test_Strings
1   Bikram  42.0         IT  85000.000000               7                sky
2  Cheetah  33.5        Ops  62000.000000              22          education
3      Dev  31.0         IT  64833.333333              15             rhythm
5   Farhan  56.0    Finance  95000.000000              33                xyz
6    Gauri  33.5        Ops  64833.333333               8                ice