## Chapter 1: Getting & knowing your data

In [3]:
import pandas as pd

In [4]:
#read_table() assumes tab-separated values defaultly.Infact not giving sep="\t" as parameter
pd.read_table(filepath_or_buffer = "data.tsv.txt")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [5]:
pd.read_table(filepath_or_buffer = "insurance.csv",sep=",")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
#read_csv() assumes comma-separated values by default.Infact not giving sep=","" as parameter

pd.read_csv(filepath_or_buffer="insurance.csv")

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
# Here we have to give "\t" in sep paramter since its not csv file its tab-separated file

order_details=pd.read_csv(filepath_or_buffer = "data.tsv.txt",sep="\t")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## 1.1 Perform Intitial Analysis

- function - ()
- Attribute

In [8]:
order_details.shape  #shape is attribute

(4622, 5)

#### Terminology alert
- rows - observation/record
- column - features/parameters

In [9]:
order_details.isnull().sum()  #chain of functions, chain of commands

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [10]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

## describe() --- very imp

In [11]:
order_details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## 1.2 Find out the Items sold in the Restaurent

In [12]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [13]:
#Dataframe is written inside the [] 
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## 1.3 Give me the list of Top 5 selling Items

In [14]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending=False).head(10)  #chain methods

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## 1.3 Give me the list of Least 5 selling Items in the restaurant

In [15]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

## Chapter 2 - Data Cleaning

In [16]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [17]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [18]:
order_details["item_price"].str.replace("$","")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [19]:
#astype() converts from one datatype to dataype
order_details["item_price"] = order_details["item_price"].str.replace("$","").astype(float)

In [20]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [21]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

#### Tasks:
1. Find out the top 5 selling items individual revenue it made
2. Find Total revenue of the top 5 items Sold
3. Find least 5 selling items revenue it made
4. Find the revenue by top 5 order id .

In [22]:
top_individual_revenue=order_details.groupby(by="item_name")["item_price"].sum().sort_values(ascending=False).head(5)  #chain methods
top_individual_revenue

item_name
Chicken Bowl           7342.73
Chicken Burrito        5575.82
Steak Burrito          3851.43
Steak Bowl             2260.19
Chips and Guacamole    2201.04
Name: item_price, dtype: float64

In [23]:
top_total_revenue=top_individual_revenue.sum()
print(top_total_revenue)

21231.21

In [24]:
least_individual_revenue= order_details.groupby("item_name")["item_price"].sum().sort_values(ascending=True).head(5)
least_individual_revenue

item_name
Chips and Mild Fresh Tomato Salsa     3.00
Veggie Crispy Tacos                   8.49
Carnitas Salad                        8.99
Crispy Tacos                         14.80
Salad                                14.80
Name: item_price, dtype: float64

In [25]:
revenue_by_orderId=order_details.groupby("order_id")["item_price"].sum().sort_values(ascending=False).head(5)
revenue_by_orderId

order_id
926     205.25
1443    160.74
1483    139.00
691     118.25
1786    114.30
Name: item_price, dtype: float64

In [26]:
revenue_by_orderId.sort_index(ascending=True)

order_id
691     118.25
926     205.25
1443    160.74
1483    139.00
1786    114.30
Name: item_price, dtype: float64

## Chapter 3: Pandas Data Structure
- 1D - Series
- 2D - DataFrame

### 3.1 Series

In [27]:
pd.Series(data=2,3)

SyntaxError: positional argument follows keyword argument (924899239.py, line 1)

In [ ]:
pd.Series(data=[1,2,"$3.5",4.5])

### 3.2 DataFrame

In [ ]:
pd.DataFrame(data= {"Roll No":[1,2,3,4,5],
                 "Name":["Yuva","Kavi","Hari","Darun","Mani"],
                 "Subject":["Maths","Science","Social","Tamil","English"],
                 "Marks":([76,87,90,86,76],[78,87,89,90,95],[89,86,75,69,83],[76,87,90,86,76],[76,87,90,86,76])
                }
)

#### Tasks
1. Create a meaningful series
2. Create a meaningful dataset using pandas dataframe with Dict 5 observation and 6 features

##### 1. Series Task

In [ ]:
days= pd.Series(data=["Weekday","Weekday","Weekday","Weekday","Weekday","Weekend","Weekend"],index=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
days.to_frame(name="Day Type")

##### 2. DataFrame Task

In [ ]:
Timetable= {"Monday":["Science","Maths","--Break--","English","Games","--Lunch--","Social","Tamil","EVS"],
            "Tuesday":["Tamil","Science Lab","--Break--","Maths","Maths","--Lunch--","Computer","Social","English"],
            "Wednesday":["Maths","Science ","--Break--","Games","Maths","--Lunch--","Tamil","Social","English"],
            "Thursday":["Tamil","Science Lab","--Break--","Maths","Maths","--Lunch--","Tamil","Social","English"],
            "Friday":["English","Social","--Break--","Tamil","Maths","--Lunch--","Computer","Social","Games"]
           }
df=pd.DataFrame(data=Timetable,index=["9.00","10.00","10.30","11.30","12.30","1.30","2.30","3.30","4.30"])
df.index.name="Time"
def highlight_breaks(val):
    if val in ["--Break--", "--Lunch--"]:
        return "background-color: yellow"
    return ""

df.style.map(highlight_breaks)
# df.style.set_caption("Class TimeTable")
# df.columns = [
#     "Mon",
#     "Tue",
#     "Wed",
#     "Thu",
#     "Fri"
# ]

#### These are used daily in data analysis and interviews.

In [ ]:
df.head()

In [ ]:
df.tail(2)  # Prints 5 observations if no Arguments mentioned

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.isnull()

## Chapter 4 - Filtering & Selection & Sorting

In [29]:
Euro_Football=pd.read_csv(filepath_or_buffer= "Euro_2012_stats_TEAM.csv")
Euro_Football

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [30]:
Euro_Football.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [ ]:
# pd.set_option('display.max_columns',None)  # To view all columns
Euro_Football

#### Filtering

In [60]:
filtered_data=Euro_Football[["Team","Goals","Red Cards","Yellow Cards"]]
filtered_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [61]:
filtered_data["Yellow Cards"]

0      9
1      7
2      4
3      5
4      6
5      4
6      9
7     16
8      5
9      7
10    12
11     6
12     6
13    11
14     7
15     5
Name: Yellow Cards, dtype: int64

#### Sorting

### 4.1 Top 5 Yellow Cards Teams

In [62]:
filtered_data.sort_values(by="Yellow Cards",ascending=False).head()

        Team  Goals  Red Cards  Yellow Cards
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11
0    Croatia      4          0             9
6     Greece      5          1             9

### 4.2 List the teams which are got Red cards

In [66]:
filtered_data[filtered_data["Red Cards"]==1]

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

### 4.3 List the team which got more than 8  yellow cards

In [67]:
filtered_data[filtered_data["Yellow Cards"]>8]

        Team  Goals  Red Cards  Yellow Cards
0    Croatia      4          0             9
6     Greece      5          1             9
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11

### Task
1. Create 5 new Questions along with script answer

##### Questions:
1. List top 5 team with high shooting accuracy
2. Which team leads highest goal
3. Which team has less players and goals >15

##### Answers:

In [80]:
Shoot_Acc_Team=Euro_Football.sort_values(by="Shooting Accuracy",ascending=False).head(5)
Shoot_Acc_Team

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17

In [79]:
High_Goal_Team = Euro_Football.sort_values(by="Goals",ascending=False).head(1)
pd.DataFrame(High_Goal_Team[["Team","Goals"]])

     Team  Goals
13  Spain     12

In [90]:

Less_Players = Euro_Football.sort_values(by="Players Used",ascending=True).head(1)
LP_with_HG = Less_Players.sort_values(by="Goals",ascending=False).head(1)
LP_with_HG[["Team","Goals","Players Used"]]

      Team  Goals  Players Used
2  Denmark      4            15

## Chapter 5 - How to deal with Missing Values

In [2]:
import pandas as pd

In [3]:
emp_data= pd.read_csv("employee_data.csv")
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [4]:
emp_data.shape

(8, 5)

### Data Cleaning -- LEVEL 1 :

#### Always Recommended: Call to client and check for right and complete data
Incase,client is asking us to perform the cleaning operations.

#### Step 1: Remove Duplicate entries/records

In [5]:
emp_data.drop_duplicates(inplace=True)  #The complete operation will imppact the original dataset
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

#### Step 2: Find out the Null/NaN entries

In [6]:
emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [7]:
emp_data.dropna(inplace=True)
emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [8]:
emp_data.shape

(4, 5)

#### Step 3: Record in a Document
* Client gave totally 7 Observations out of which 3 entries are removed because those records do not have complete information

#### Step 4: Get further Approval
* Send this step3 info to client and get the approval to proceed for Model Building or Model Training

In [9]:
emp_data.isnull().sum()  #check for null data to go further

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

### Data Cleaning -- LEVEL 2 :

In [12]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [97]:
added_emp_data=pd.read_excel("employee_data.xlsx",sheet_name=1) 
added_emp_data

             Name Age Department Salary            Join_Date
0          Rajesh  29        Ops  60000          21-05-2023
1           Nasir  31    IT Tech  62000  2020-12-11 00:00:00
2         Mathiew   —    Support  58000          15-01-2025
3         Gilbert  29        Ops  60000          21-05-2021
4           Kevin  28    Support  61000          30-07-2024
5           Navin  35    Support  72000          19-08-2023
6               —  40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan  31    IT Tech      —  2020-12-11 00:00:00
8       Kuppusamy  28        Ops      —          21-05-2021
9           Ajesh  28    Support      —          30-07-2024
10           Diya  31    IT Tech  63000  2020-12-11 00:00:00
11        Mathiew   —    Support  58000          15-01-2025
12  Jagadheeswari  28    IT Tech      —                   —
13           Mani  28        Ops      —          21-05-2021

In [98]:
added_emp_data.duplicated()  #check for duplicate rows

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
dtype: bool

#### Step 1: Drop Duplicates

In [99]:
added_emp_data.drop_duplicates(inplace=True)
added_emp_data

             Name Age Department Salary            Join_Date
0          Rajesh  29        Ops  60000          21-05-2023
1           Nasir  31    IT Tech  62000  2020-12-11 00:00:00
2         Mathiew   —    Support  58000          15-01-2025
3         Gilbert  29        Ops  60000          21-05-2021
4           Kevin  28    Support  61000          30-07-2024
5           Navin  35    Support  72000          19-08-2023
6               —  40    IT Tech  64000  2022-10-09 00:00:00
7          Roshan  31    IT Tech      —  2020-12-11 00:00:00
8       Kuppusamy  28        Ops      —          21-05-2021
9           Ajesh  28    Support      —          30-07-2024
10           Diya  31    IT Tech  63000  2020-12-11 00:00:00
12  Jagadheeswari  28    IT Tech      —                   —
13           Mani  28        Ops      —          21-05-2021

#### Step 2: Identify Null entries

In [100]:
import numpy as np
added_emp_data.replace('—', np.nan,inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15256\3651173347.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  added_emp_data.replace('—', np.nan,inplace=True)

In [101]:
added_emp_data.isna().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     0
dtype: int64

##### Join_Date has one null value but the function considering that as a actual date. So fix this

In [102]:
added_emp_data

             Name   Age Department   Salary            Join_Date
0          Rajesh  29.0        Ops  60000.0          21-05-2023
1           Nasir  31.0    IT Tech  62000.0  2020-12-11 00:00:00
2         Mathiew   NaN    Support  58000.0          15-01-2025
3         Gilbert  29.0        Ops  60000.0          21-05-2021
4           Kevin  28.0    Support  61000.0          30-07-2024
5           Navin  35.0    Support  72000.0          19-08-2023
6             NaN  40.0    IT Tech  64000.0  2022-10-09 00:00:00
7          Roshan  31.0    IT Tech      NaN  2020-12-11 00:00:00
8       Kuppusamy  28.0        Ops      NaN          21-05-2021
9           Ajesh  28.0    Support      NaN          30-07-2024
10           Diya  31.0    IT Tech  63000.0  2020-12-11 00:00:00
12  Jagadheeswari  28.0    IT Tech      NaN                   —
13           Mani  28.0        Ops      NaN          21-05-2021

In [103]:
added_emp_data['Join_Date'] = pd.to_datetime(added_emp_data['Join_Date'], errors='coerce',)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15256\4228332072.py:1: UserWarning: Parsing dates in %d-%m-%Y  format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  added_emp_data['Join_Date'] = pd.to_datetime(added_emp_data['Join_Date'], errors='coerce',)

In [104]:
added_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        5
Join_Date     1
dtype: int64

In [105]:
added_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-12-11
2         Mathiew   NaN    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-10-09
7          Roshan  31.0    IT Tech      NaN 2020-12-11
8       Kuppusamy  28.0        Ops      NaN 2021-05-21
9           Ajesh  28.0    Support      NaN 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-12-11
12  Jagadheeswari  28.0    IT Tech      NaN        NaT
13           Mani  28.0        Ops      NaN 2021-05-21

### Step 3: Go for best Imputation

In [106]:
added_emp_data["Department"].unique()

array(['Ops', 'IT Tech', 'Support'], dtype=object)

In [107]:
added_emp_data[added_emp_data["Department"]=="IT Tech"]

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-12-11
6             NaN  40.0    IT Tech  64000.0 2022-10-09
7          Roshan  31.0    IT Tech      NaN 2020-12-11
10           Diya  31.0    IT Tech  63000.0 2020-12-11
12  Jagadheeswari  28.0    IT Tech      NaN        NaT

In [108]:
added_emp_data[added_emp_data["Department"]=="Support"]

      Name   Age Department   Salary  Join_Date
2  Mathiew   NaN    Support  58000.0 2025-01-15
4    Kevin  28.0    Support  61000.0 2024-07-30
5    Navin  35.0    Support  72000.0 2023-08-19
9    Ajesh  28.0    Support      NaN 2024-07-30

In [109]:
added_emp_data[added_emp_data["Department"]=="Ops"]

         Name   Age Department   Salary  Join_Date
0      Rajesh  29.0        Ops  60000.0 2023-05-21
3     Gilbert  29.0        Ops  60000.0 2021-05-21
8   Kuppusamy  28.0        Ops      NaN 2021-05-21
13       Mani  28.0        Ops      NaN 2021-05-21

### Task
1. Impute the relevant values in Salary column wherever its's NaN,based on dept filtering.
2. Impute Mathiew's age as 27

In [110]:
added_emp_data[(added_emp_data["Salary"].isna()) & (added_emp_data["Department"]=="Support")]

    Name   Age Department  Salary  Join_Date
9  Ajesh  28.0    Support     NaN 2024-07-30

##### Using loc[index_value,col_name] to assign value to particular entry

In [112]:
added_emp_data.loc[9, 'Salary'] = 61000.00

In [113]:
added_emp_data[added_emp_data["Department"]=="Support"]

      Name   Age Department   Salary  Join_Date
2  Mathiew   NaN    Support  58000.0 2025-01-15
4    Kevin  28.0    Support  61000.0 2024-07-30
5    Navin  35.0    Support  72000.0 2023-08-19
9    Ajesh  28.0    Support  61000.0 2024-07-30

In [114]:
added_emp_data[(added_emp_data["Age"].isna()) & (added_emp_data["Department"]=="Support") ]

      Name  Age Department   Salary  Join_Date
2  Mathiew  NaN    Support  58000.0 2025-01-15

In [115]:
added_emp_data.loc[2,'Age']=27

In [116]:
added_emp_data[added_emp_data["Department"]=="Support"]

      Name   Age Department   Salary  Join_Date
2  Mathiew  27.0    Support  58000.0 2025-01-15
4    Kevin  28.0    Support  61000.0 2024-07-30
5    Navin  35.0    Support  72000.0 2023-08-19
9    Ajesh  28.0    Support  61000.0 2024-07-30

In [119]:
added_emp_data[added_emp_data["Department"]=="IT Tech"]

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-12-11
6             NaN  40.0    IT Tech  64000.0 2022-10-09
7          Roshan  31.0    IT Tech      NaN 2020-12-11
10           Diya  31.0    IT Tech  63000.0 2020-12-11
12  Jagadheeswari  28.0    IT Tech      NaN        NaT

In [117]:
added_emp_data[(added_emp_data["Salary"].isna()) & (added_emp_data["Department"]=="IT Tech")]

             Name   Age Department  Salary  Join_Date
7          Roshan  31.0    IT Tech     NaN 2020-12-11
12  Jagadheeswari  28.0    IT Tech     NaN        NaT

In [122]:
added_emp_data.loc[[7,12],'Salary']=added_emp_data.loc[[1,7,10],'Salary'].mean()

In [123]:
added_emp_data[added_emp_data["Department"]=="IT Tech"]

             Name   Age Department   Salary  Join_Date
1           Nasir  31.0    IT Tech  62000.0 2020-12-11
6             NaN  40.0    IT Tech  64000.0 2022-10-09
7          Roshan  31.0    IT Tech  62500.0 2020-12-11
10           Diya  31.0    IT Tech  63000.0 2020-12-11
12  Jagadheeswari  28.0    IT Tech  62500.0        NaT

In [124]:
added_emp_data

             Name   Age Department   Salary  Join_Date
0          Rajesh  29.0        Ops  60000.0 2023-05-21
1           Nasir  31.0    IT Tech  62000.0 2020-12-11
2         Mathiew  27.0    Support  58000.0 2025-01-15
3         Gilbert  29.0        Ops  60000.0 2021-05-21
4           Kevin  28.0    Support  61000.0 2024-07-30
5           Navin  35.0    Support  72000.0 2023-08-19
6             NaN  40.0    IT Tech  64000.0 2022-10-09
7          Roshan  31.0    IT Tech  62500.0 2020-12-11
8       Kuppusamy  28.0        Ops      NaN 2021-05-21
9           Ajesh  28.0    Support  61000.0 2024-07-30
10           Diya  31.0    IT Tech  63000.0 2020-12-11
12  Jagadheeswari  28.0    IT Tech  62500.0        NaT
13           Mani  28.0        Ops      NaN 2021-05-21